package com.bellinfo.entities;

// Generated Jul 31, 2015 10:14:40 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AdminAddFaculty generated by hbm2java
 */
@Entity
@Table(name = "admin_add_faculty", schema = "public")
public class AdminAddFaculty implements java.io.Serializable {

	private long adminAddfacultyId;
	private BellinfoUserLogin bellinfoUserLogin;
	private String adminAddfacultyName;
	private String adminAddfacultyTechnology;
	private String adminAddfacultyPassword;
	private Date adminAddfacultyCreateddate;
	private Long adminAddfacultySalary;

	public AdminAddFaculty() {
	}

	public AdminAddFaculty(long adminAddfacultyId) {
		this.adminAddfacultyId = adminAddfacultyId;
	}

	public AdminAddFaculty(long adminAddfacultyId,
			BellinfoUserLogin bellinfoUserLogin, String adminAddfacultyName,
			String adminAddfacultyTechnology, String adminAddfacultyPassword,
			Date adminAddfacultyCreateddate, Long adminAddfacultySalary) {
		this.adminAddfacultyId = adminAddfacultyId;
		this.bellinfoUserLogin = bellinfoUserLogin;
		this.adminAddfacultyName = adminAddfacultyName;
		this.adminAddfacultyTechnology = adminAddfacultyTechnology;
		this.adminAddfacultyPassword = adminAddfacultyPassword;
		this.adminAddfacultyCreateddate = adminAddfacultyCreateddate;
		this.adminAddfacultySalary = adminAddfacultySalary;
	}

	@Id
	@Column(name = "admin_addfaculty_id", unique = true, nullable = false)
	public long getAdminAddfacultyId() {
		return this.adminAddfacultyId;
	}

	public void setAdminAddfacultyId(long adminAddfacultyId) {
		this.adminAddfacultyId = adminAddfacultyId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id")
	public BellinfoUserLogin getBellinfoUserLogin() {
		return this.bellinfoUserLogin;
	}

	public void setBellinfoUserLogin(BellinfoUserLogin bellinfoUserLogin) {
		this.bellinfoUserLogin = bellinfoUserLogin;
	}

	@Column(name = "admin_addfaculty_name", length = 100)
	public String getAdminAddfacultyName() {
		return this.adminAddfacultyName;
	}

	public void setAdminAddfacultyName(String adminAddfacultyName) {
		this.adminAddfacultyName = adminAddfacultyName;
	}

	@Column(name = "admin_addfaculty_technology", length = 100)
	public String getAdminAddfacultyTechnology() {
		return this.adminAddfacultyTechnology;
	}

	public void setAdminAddfacultyTechnology(String adminAddfacultyTechnology) {
		this.adminAddfacultyTechnology = adminAddfacultyTechnology;
	}

	@Column(name = "admin_addfaculty_password", length = 100)
	public String getAdminAddfacultyPassword() {
		return this.adminAddfacultyPassword;
	}

	public void setAdminAddfacultyPassword(String adminAddfacultyPassword) {
		this.adminAddfacultyPassword = adminAddfacultyPassword;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "admin_addfaculty_createddate", length = 29)
	public Date getAdminAddfacultyCreateddate() {
		return this.adminAddfacultyCreateddate;
	}

	public void setAdminAddfacultyCreateddate(Date adminAddfacultyCreateddate) {
		this.adminAddfacultyCreateddate = adminAddfacultyCreateddate;
	}

	@Column(name = "admin_addfaculty_salary")
	public Long getAdminAddfacultySalary() {
		return this.adminAddfacultySalary;
	}

	public void setAdminAddfacultySalary(Long adminAddfacultySalary) {
		this.adminAddfacultySalary = adminAddfacultySalary;
	}

}
