package com.bellinfo.entities;

// Generated Jul 31, 2015 10:14:40 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AdminProxy generated by hbm2java
 */
@Entity
@Table(name = "admin_proxy", schema = "public")
public class AdminProxy implements java.io.Serializable {

	private long adminProxyId;
	private BellinfoUserLogin bellinfoUserLogin;
	private String proxyName;
	private Date proxyFromTime;
	private Date proxyToTime;

	public AdminProxy() {
	}

	public AdminProxy(long adminProxyId) {
		this.adminProxyId = adminProxyId;
	}

	public AdminProxy(long adminProxyId, BellinfoUserLogin bellinfoUserLogin,
			String proxyName, Date proxyFromTime, Date proxyToTime) {
		this.adminProxyId = adminProxyId;
		this.bellinfoUserLogin = bellinfoUserLogin;
		this.proxyName = proxyName;
		this.proxyFromTime = proxyFromTime;
		this.proxyToTime = proxyToTime;
	}

	@Id
	@Column(name = "admin_proxy_id", unique = true, nullable = false)
	public long getAdminProxyId() {
		return this.adminProxyId;
	}

	public void setAdminProxyId(long adminProxyId) {
		this.adminProxyId = adminProxyId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id")
	public BellinfoUserLogin getBellinfoUserLogin() {
		return this.bellinfoUserLogin;
	}

	public void setBellinfoUserLogin(BellinfoUserLogin bellinfoUserLogin) {
		this.bellinfoUserLogin = bellinfoUserLogin;
	}

	@Column(name = "proxy_name", length = 100)
	public String getProxyName() {
		return this.proxyName;
	}

	public void setProxyName(String proxyName) {
		this.proxyName = proxyName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "proxy_from_time", length = 29)
	public Date getProxyFromTime() {
		return this.proxyFromTime;
	}

	public void setProxyFromTime(Date proxyFromTime) {
		this.proxyFromTime = proxyFromTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "proxy_to_time", length = 29)
	public Date getProxyToTime() {
		return this.proxyToTime;
	}

	public void setProxyToTime(Date proxyToTime) {
		this.proxyToTime = proxyToTime;
	}

}
