package com.bellinfo.entities;

// Generated Jul 31, 2015 10:14:40 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;

import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * BellinfoUserBackgroundinformation generated by hbm2java
 */
@Entity
@Table(name = "bellinfo_user_backgroundinformation", schema = "public")
public class BellinfoUserBackgroundinformation implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1744766045892542515L;
	private long userBackgroundId;
	private BellinfoUserLogin bellinfoUserLogin;
	private String userBackgroundUniversity;
	private String userTechnology;
	private String userBackgroundMastersgroup;

	public BellinfoUserBackgroundinformation() {
	}

	public BellinfoUserBackgroundinformation(long userBackgroundId) {
		this.userBackgroundId = userBackgroundId;
	}

	public BellinfoUserBackgroundinformation(long userBackgroundId,
			BellinfoUserLogin bellinfoUserLogin,
			String userBackgroundUniversity, String userTechnology,
			String userBackgroundMastersgroup) {
		this.userBackgroundId = userBackgroundId;
		this.bellinfoUserLogin = bellinfoUserLogin;
		this.userBackgroundUniversity = userBackgroundUniversity;
		this.userTechnology = userTechnology;
		this.userBackgroundMastersgroup = userBackgroundMastersgroup;
	}

	@Id
	@Column(name = "user_background_id", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	public long getUserBackgroundId() {
		return this.userBackgroundId;
	}

	public void setUserBackgroundId(long userBackgroundId) {
		this.userBackgroundId = userBackgroundId;
	}

	@OneToOne(fetch = FetchType.LAZY/*,cascade=CascadeType.ALL*/)
	@JoinColumn(name = "user_id")
	public BellinfoUserLogin getBellinfoUserLogin() {
		return this.bellinfoUserLogin;
	}

	public void setBellinfoUserLogin(BellinfoUserLogin bellinfoUserLogin) {
		this.bellinfoUserLogin = bellinfoUserLogin;
	}

	@Column(name = "user_background_university", length = 300)
	public String getUserBackgroundUniversity() {
		return this.userBackgroundUniversity;
	}

	public void setUserBackgroundUniversity(String userBackgroundUniversity) {
		this.userBackgroundUniversity = userBackgroundUniversity;
	}

	@Column(name = "user_technology", length = 100)
	public String getUserTechnology() {
		return this.userTechnology;
	}

	public void setUserTechnology(String userTechnology) {
		this.userTechnology = userTechnology;
	}

	@Column(name = "user_background_mastersgroup", length = 100)
	public String getUserBackgroundMastersgroup() {
		return this.userBackgroundMastersgroup;
	}

	public void setUserBackgroundMastersgroup(String userBackgroundMastersgroup) {
		this.userBackgroundMastersgroup = userBackgroundMastersgroup;
	}

}
