package com.bellinfo.entities;

// Generated Jul 31, 2015 10:14:40 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;

import javax.persistence.OneToOne;
import javax.persistence.Table;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * BellinfoUser generated by hbm2java
 */
@Entity
@Table(name = "bellinfo_user", schema = "public")
@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
public class BellinfoUser implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4511386929196205050L;
	private long userProfileId;
	private BellinfoUserLogin bellinfoUserLogin;
	private String userFirstName;
	private String userLastName;
	private String userEmailid;
	private Boolean userGender;
	private String userPhoneNumber;

	public BellinfoUser() {
	}

	public BellinfoUser(long userProfileId, BellinfoUserLogin bellinfoUserLogin) {
		this.userProfileId = userProfileId;
		this.bellinfoUserLogin = bellinfoUserLogin;
	}

	public BellinfoUser(long userProfileId,
			BellinfoUserLogin bellinfoUserLogin, String userFirstName,
			String userLastName, String userEmailid, Boolean userGender,
			String userPhoneNumber) {
		this.userProfileId = userProfileId;
		this.bellinfoUserLogin = bellinfoUserLogin;
		this.userFirstName = userFirstName;
		this.userLastName = userLastName;
		this.userEmailid = userEmailid;
		this.userGender = userGender;
		this.userPhoneNumber = userPhoneNumber;
	}

	@Id
	@Column(name = "user_profile_id", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	public long getUserProfileId() {
		return this.userProfileId;
	}

	public void setUserProfileId(long userProfileId) {
		this.userProfileId = userProfileId;
	}

	@OneToOne(fetch = FetchType.LAZY/*,cascade=CascadeType.ALL*/)
	@JoinColumn(name = "user_id", nullable = false)
	public BellinfoUserLogin getBellinfoUserLogin() {
		return this.bellinfoUserLogin;
	}

	public void setBellinfoUserLogin(BellinfoUserLogin bellinfoUserLogin) {
		this.bellinfoUserLogin = bellinfoUserLogin;
	}

	@Column(name = "user_first_name", length = 100)
	public String getUserFirstName() {
		return this.userFirstName;
	}

	public void setUserFirstName(String userFirstName) {
		this.userFirstName = userFirstName;
	}

	@Column(name = "user_last_name", length = 100)
	public String getUserLastName() {
		return this.userLastName;
	}

	public void setUserLastName(String userLastName) {
		this.userLastName = userLastName;
	}

	@Column(name = "user_emailid", length = 100)
	public String getUserEmailid() {
		return this.userEmailid;
	}

	public void setUserEmailid(String userEmailid) {
		this.userEmailid = userEmailid;
	}

	@Column(name = "user_gender")
	public Boolean getUserGender() {
		return this.userGender;
	}

	public void setUserGender(Boolean userGender) {
		this.userGender = userGender;
	}

	@Column(name = "user_phone_number", length = 100)
	public String getUserPhoneNumber() {
		return this.userPhoneNumber;
	}

	public void setUserPhoneNumber(String userPhoneNumber) {
		this.userPhoneNumber = userPhoneNumber;
	}

}
