package com.bellinfo.entities;

// Generated Jul 31, 2015 10:14:40 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BellinfoUserStickynotes generated by hbm2java
 */
@Entity
@Table(name = "bellinfo_user_stickynotes", schema = "public")
public class BellinfoUserStickynotes implements java.io.Serializable {

	private long userStickynotesId;
	private BellinfoUserLogin bellinfoUserLogin;
	private String userStickynotesPost;
	private Date userStickynotesCreateddate;

	public BellinfoUserStickynotes() {
	}

	public BellinfoUserStickynotes(long userStickynotesId) {
		this.userStickynotesId = userStickynotesId;
	}

	public BellinfoUserStickynotes(long userStickynotesId,
			BellinfoUserLogin bellinfoUserLogin, String userStickynotesPost,
			Date userStickynotesCreateddate) {
		this.userStickynotesId = userStickynotesId;
		this.bellinfoUserLogin = bellinfoUserLogin;
		this.userStickynotesPost = userStickynotesPost;
		this.userStickynotesCreateddate = userStickynotesCreateddate;
	}

	@Id
	@Column(name = "user_stickynotes_id", unique = true, nullable = false)
	public long getUserStickynotesId() {
		return this.userStickynotesId;
	}

	public void setUserStickynotesId(long userStickynotesId) {
		this.userStickynotesId = userStickynotesId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id")
	public BellinfoUserLogin getBellinfoUserLogin() {
		return this.bellinfoUserLogin;
	}

	public void setBellinfoUserLogin(BellinfoUserLogin bellinfoUserLogin) {
		this.bellinfoUserLogin = bellinfoUserLogin;
	}

	@Column(name = "user_stickynotes_post", length = 200)
	public String getUserStickynotesPost() {
		return this.userStickynotesPost;
	}

	public void setUserStickynotesPost(String userStickynotesPost) {
		this.userStickynotesPost = userStickynotesPost;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "user_stickynotes_createddate", length = 29)
	public Date getUserStickynotesCreateddate() {
		return this.userStickynotesCreateddate;
	}

	public void setUserStickynotesCreateddate(Date userStickynotesCreateddate) {
		this.userStickynotesCreateddate = userStickynotesCreateddate;
	}

}
