package com.bellinfo.entities;

// Generated Jul 31, 2015 10:14:40 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProxyAvailability generated by hbm2java
 */
@Entity
@Table(name = "proxy_availability", schema = "public")
public class ProxyAvailability implements java.io.Serializable {

	private long availabilityId;
	private BellinfoUserLogin bellinfoUserLogin;
	private String proxyName;
	private Date userBookingFrom;
	private Date userBookingTo;

	public ProxyAvailability() {
	}

	public ProxyAvailability(long availabilityId) {
		this.availabilityId = availabilityId;
	}

	public ProxyAvailability(long availabilityId,
			BellinfoUserLogin bellinfoUserLogin, String proxyName,
			Date userBookingFrom, Date userBookingTo) {
		this.availabilityId = availabilityId;
		this.bellinfoUserLogin = bellinfoUserLogin;
		this.proxyName = proxyName;
		this.userBookingFrom = userBookingFrom;
		this.userBookingTo = userBookingTo;
	}

	@Id
	@Column(name = "availability_id", unique = true, nullable = false)
	public long getAvailabilityId() {
		return this.availabilityId;
	}

	public void setAvailabilityId(long availabilityId) {
		this.availabilityId = availabilityId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id")
	public BellinfoUserLogin getBellinfoUserLogin() {
		return this.bellinfoUserLogin;
	}

	public void setBellinfoUserLogin(BellinfoUserLogin bellinfoUserLogin) {
		this.bellinfoUserLogin = bellinfoUserLogin;
	}

	@Column(name = "proxy_name", length = 100)
	public String getProxyName() {
		return this.proxyName;
	}

	public void setProxyName(String proxyName) {
		this.proxyName = proxyName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "user_booking_from", length = 29)
	public Date getUserBookingFrom() {
		return this.userBookingFrom;
	}

	public void setUserBookingFrom(Date userBookingFrom) {
		this.userBookingFrom = userBookingFrom;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "user_booking_to", length = 29)
	public Date getUserBookingTo() {
		return this.userBookingTo;
	}

	public void setUserBookingTo(Date userBookingTo) {
		this.userBookingTo = userBookingTo;
	}

}
