package com.bellinfo.entities;

// Generated Jul 31, 2015 10:14:40 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserResumeMetadata generated by hbm2java
 */
@Entity
@Table(name = "user_resume_metadata", schema = "public")
public class UserResumeMetadata implements java.io.Serializable {

	private long userResumeMetadataId;
	private UserResume userResume;
	private String resumePropertyName;
	private String resumePropertyValue;
	private Date imageMetadataCreatedDate;

	public UserResumeMetadata() {
	}

	public UserResumeMetadata(long userResumeMetadataId) {
		this.userResumeMetadataId = userResumeMetadataId;
	}

	public UserResumeMetadata(long userResumeMetadataId, UserResume userResume,
			String resumePropertyName, String resumePropertyValue,
			Date imageMetadataCreatedDate) {
		this.userResumeMetadataId = userResumeMetadataId;
		this.userResume = userResume;
		this.resumePropertyName = resumePropertyName;
		this.resumePropertyValue = resumePropertyValue;
		this.imageMetadataCreatedDate = imageMetadataCreatedDate;
	}

	@Id
	@Column(name = "user_resume_metadata_id", unique = true, nullable = false)
	public long getUserResumeMetadataId() {
		return this.userResumeMetadataId;
	}

	public void setUserResumeMetadataId(long userResumeMetadataId) {
		this.userResumeMetadataId = userResumeMetadataId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_resume_id")
	public UserResume getUserResume() {
		return this.userResume;
	}

	public void setUserResume(UserResume userResume) {
		this.userResume = userResume;
	}

	@Column(name = "resume_property_name", length = 100)
	public String getResumePropertyName() {
		return this.resumePropertyName;
	}

	public void setResumePropertyName(String resumePropertyName) {
		this.resumePropertyName = resumePropertyName;
	}

	@Column(name = "resume_property_value", length = 100)
	public String getResumePropertyValue() {
		return this.resumePropertyValue;
	}

	public void setResumePropertyValue(String resumePropertyValue) {
		this.resumePropertyValue = resumePropertyValue;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "image_metadata_created_date", length = 29)
	public Date getImageMetadataCreatedDate() {
		return this.imageMetadataCreatedDate;
	}

	public void setImageMetadataCreatedDate(Date imageMetadataCreatedDate) {
		this.imageMetadataCreatedDate = imageMetadataCreatedDate;
	}

}
