package com.bellinfo.entities;

// Generated Jul 31, 2015 10:14:40 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserResume generated by hbm2java
 */
@Entity
@Table(name = "user_resume", schema = "public")
public class UserResume implements java.io.Serializable {

	private long userResumeId;
	private BellinfoUserLogin bellinfoUserLogin;
	private Date userResumeUploadedDate;
	private String userResumeDescription;
	private String userResumeTechnologyType;
	private Set<UserResumeMetadata> userResumeMetadatas = new HashSet<UserResumeMetadata>(
			0);
	private Set<UserResumeData> userResumeDatas = new HashSet<UserResumeData>(0);

	public UserResume() {
	}

	public UserResume(long userResumeId) {
		this.userResumeId = userResumeId;
	}

	public UserResume(long userResumeId, BellinfoUserLogin bellinfoUserLogin,
			Date userResumeUploadedDate, String userResumeDescription,
			String userResumeTechnologyType,
			Set<UserResumeMetadata> userResumeMetadatas,
			Set<UserResumeData> userResumeDatas) {
		this.userResumeId = userResumeId;
		this.bellinfoUserLogin = bellinfoUserLogin;
		this.userResumeUploadedDate = userResumeUploadedDate;
		this.userResumeDescription = userResumeDescription;
		this.userResumeTechnologyType = userResumeTechnologyType;
		this.userResumeMetadatas = userResumeMetadatas;
		this.userResumeDatas = userResumeDatas;
	}

	@Id
	@Column(name = "user_resume_id", unique = true, nullable = false)
	public long getUserResumeId() {
		return this.userResumeId;
	}

	public void setUserResumeId(long userResumeId) {
		this.userResumeId = userResumeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id")
	public BellinfoUserLogin getBellinfoUserLogin() {
		return this.bellinfoUserLogin;
	}

	public void setBellinfoUserLogin(BellinfoUserLogin bellinfoUserLogin) {
		this.bellinfoUserLogin = bellinfoUserLogin;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "user_resume_uploaded_date", length = 29)
	public Date getUserResumeUploadedDate() {
		return this.userResumeUploadedDate;
	}

	public void setUserResumeUploadedDate(Date userResumeUploadedDate) {
		this.userResumeUploadedDate = userResumeUploadedDate;
	}

	@Column(name = "user_resume_description", length = 200)
	public String getUserResumeDescription() {
		return this.userResumeDescription;
	}

	public void setUserResumeDescription(String userResumeDescription) {
		this.userResumeDescription = userResumeDescription;
	}

	@Column(name = "user_resume_technology_type", length = 100)
	public String getUserResumeTechnologyType() {
		return this.userResumeTechnologyType;
	}

	public void setUserResumeTechnologyType(String userResumeTechnologyType) {
		this.userResumeTechnologyType = userResumeTechnologyType;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userResume")
	public Set<UserResumeMetadata> getUserResumeMetadatas() {
		return this.userResumeMetadatas;
	}

	public void setUserResumeMetadatas(
			Set<UserResumeMetadata> userResumeMetadatas) {
		this.userResumeMetadatas = userResumeMetadatas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userResume")
	public Set<UserResumeData> getUserResumeDatas() {
		return this.userResumeDatas;
	}

	public void setUserResumeDatas(Set<UserResumeData> userResumeDatas) {
		this.userResumeDatas = userResumeDatas;
	}

}
