package com.bellinfo.entities;

// Generated Jul 31, 2015 10:14:40 PM by Hibernate Tools 4.3.1

import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserRole generated by hbm2java
 */
@Entity
@Table(name = "user_role", schema = "public")
public class UserRole implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2278191488307412670L;
	private long userRoleId;
	private BellinfoUserLogin bellinfoUserLogin;
	private String userRoleUsername;
	private String userRoleRole;
	private Date userRoleCreatedDate;

	public UserRole() {
	}

	public UserRole(long userRoleId) {
		this.userRoleId = userRoleId;
	}

	public UserRole(long userRoleId, BellinfoUserLogin bellinfoUserLogin,
			String userRoleUsername, String userRoleRole,
			Date userRoleCreatedDate) {
		this.userRoleId = userRoleId;
		this.bellinfoUserLogin = bellinfoUserLogin;
		this.userRoleUsername = userRoleUsername;
		this.userRoleRole = userRoleRole;
		this.userRoleCreatedDate = userRoleCreatedDate;
	}

	@Id
	@Column(name = "user_role_id", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	public long getUserRoleId() {
		return this.userRoleId;
	}

	public void setUserRoleId(long userRoleId) {
		this.userRoleId = userRoleId;
	}

	@OneToOne(fetch = FetchType.LAZY/*,cascade=CascadeType.ALL*/)
	@JoinColumn(name = "user_id")
	public BellinfoUserLogin getBellinfoUserLogin() {
		return this.bellinfoUserLogin;
	}

	public void setBellinfoUserLogin(BellinfoUserLogin bellinfoUserLogin) {
		this.bellinfoUserLogin = bellinfoUserLogin;
	}

	@Column(name = "user_role_username", length = 100)
	public String getUserRoleUsername() {
		return this.userRoleUsername;
	}

	public void setUserRoleUsername(String userRoleUsername) {
		this.userRoleUsername = userRoleUsername;
	}

	@Column(name = "user_role_role", length = 100)
	public String getUserRoleRole() {
		return this.userRoleRole;
	}

	public void setUserRoleRole(String userRoleRole) {
		this.userRoleRole = userRoleRole;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "user_role_created_date", length = 29)
	public Date getUserRoleCreatedDate() {
		return this.userRoleCreatedDate;
	}

	public void setUserRoleCreatedDate(Date userRoleCreatedDate) {
		this.userRoleCreatedDate = userRoleCreatedDate;
	}

}
